[tool.poetry]
name = "pdf-malware-detector"
version = "0.1.0"
description = ""
authors = ["Salman Wiharja"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.3"
Flask = "3.0.3"
colorama = "0.4.6"
joblib = "1.4.2"
numpy = "1.26.4"
pandas = "2.2.2"
pdfid = "1.1.3"
scikit-learn = "1.3.2"
scipy = "1.13.1"
tqdm = "4.66.4"
virtualenv = "20.26.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
